# Generated by Django 4.2.7 on 2023-11-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_order_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
