# Generated by Django 4.2.7 on 2023-11-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0010_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
