# Generated by Django 4.2.7 on 2023-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=2, max_length=455, unique=True),
            preserve_default=False,
        ),
    ]
